version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  test-and-deploy:
    executor:
      name: node/default
      tag: '16.17'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Test << pipeline.git.branch >>
          command: yarn run test
      - run:
          name: Build << pipeline.git.branch >>
          command: PUBLIC_URL=/circle-ci-test yarn run build
      - run:
          name: Setup git user
          command: <
            git config --global user.email "mrpachara@gmail.com" && \
            git config --global user.name "Pachara Tinamas"
      - run:
          name: Deploy to gh-pages
          command: yarn run deploy

workflows:
  test_and_deploy_my_app:
    jobs:
      - test-and-deploy
