version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  install-and-test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/run:
          install-yarn: true
          node-version: '16.13'
          yarn-run: test

workflows:
  test_my_app:
    jobs:
      - install-and-test
